osx fix

diff --git a/scripts/aziona-aws-assume-role b/scripts/aziona-aws-assume-role
--- a/scripts/aziona-aws-assume-role
+++ b/scripts/aziona-aws-assume-role
@@ -52,9 +52,26 @@ getargs() {
   [[ "${arg_ROLE:-}" != "" ]] || (echo 'Args: -r or --role [required]' && exit 1)
 }
 
+getargs_osx() {
+  arg_COMPANY=${1:-}
+  arg_COMPANY=${2:-}
+  arg_ROLE=${3:-}
+
+  [[ "${arg_COMPANY:-}" != "" ]] || (echo 'Args: -c or --company [required]' && exit 1)
+  [[ "${arg_ENV:-}" != "" ]] || (echo 'Args: -e or --env [required]' && exit 1)
+  [[ "${arg_ROLE:-}" != "" ]] || (echo 'Args: -r or --role [required]' && exit 1)
+}
 
 main() {
-  getargs "$@"
+  if [ "$(uname)" == "Darwin" ]; then
+    getargs_osx "$@"
+  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+    getargs "$@"
+  else
+      echo "OS not valid"
+      exit 1
+  fi
+
   source <( aziona-environment --company $arg_COMPANY --env $arg_ENV )
 
   # Assume role aws
diff --git a/scripts/aziona-aws-ecr-login b/scripts/aziona-aws-ecr-login
--- a/scripts/aziona-aws-ecr-login
+++ b/scripts/aziona-aws-ecr-login
@@ -53,8 +53,26 @@ getargs() {
   [[ "${arg_PROFILE:-}" != "" ]] || (echo 'Args: -p or --profile [required]' && exit 1)
 }
 
+getargs_osx() {
+  arg_COMPANY=${1:-}
+  arg_ENV=${2:-}
+  arg_PROFILE=${3:-}
+
+  [[ "${arg_COMPANY:-}" != "" ]] || (echo 'Args: -c or --company [required]' && exit 1)
+  [[ "${arg_ENV:-}" != "" ]] || (echo 'Args: -e or --env [required]' && exit 1)
+  [[ "${arg_PROFILE:-}" != "" ]] || (echo 'Args: -p or --profile [required]' && exit 1)
+}
+
 main() {
-  getargs "$@"
+  if [ "$(uname)" == "Darwin" ]; then
+    getargs_osx "$@"
+  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+    getargs "$@"
+  else
+      echo "OS not valid"
+      exit 1
+  fi
+
   source <( setkubeconfig $arg_COMPANY $arg_ENV )
   aws --profile "${arg_PROFILE}" ecr get-login-password --region "${ECR_AWS_REGION}" | docker login --username AWS --password-stdin "${ECR_ACCOUNT_ID}".dkr.ecr."${ECR_AWS_REGION}".amazonaws.com
 }
diff --git a/scripts/aziona-environment b/scripts/aziona-environment
--- a/scripts/aziona-environment
+++ b/scripts/aziona-environment
@@ -57,6 +57,14 @@ getargs() {
   [[ "${arg_ENV:-}" != "" ]] || (echo 'Args: -e or --env [required]' && exit 1)
 }
 
+getargs_osx() {
+  arg_COMPANY=${1:-}
+  arg_ENV=${2:-}
+
+  [[ "${arg_COMPANY:-}" != "" ]] || (echo 'Args: -c or --company [required]' && exit 1)
+  [[ "${arg_ENV:-}" != "" ]] || (echo 'Args: -e or --env [required]' && exit 1)
+}
+
 _darwin(){
   if [ -z "${arg_CONFIG_PATH:-}" ]; then 
     WORKSPACE_PREFIX=${PROJECTS_PREFIX:-"/Users/$(whoami)/Documents/projects"}/${arg_COMPANY}
@@ -106,8 +114,17 @@ setconfig() {
   echo "source ${DEVOPS_PATH}/venv/bin/activate > /dev/null 2>&1"
 }
 
+
 main() {
-  getargs "$@"
+  if [ "$(uname)" == "Darwin" ]; then
+    getargs_osx "$@"
+  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+    getargs "$@"
+  else
+      echo "OS not valid"
+      exit 1
+  fi
+
   setconfig
 }
 
