refactoring setup with dir .aziona

diff --git a/scripts/aziona-aws-ecr-login b/scripts/aziona-aws-ecr-login
--- a/scripts/aziona-aws-ecr-login
+++ b/scripts/aziona-aws-ecr-login
@@ -1,12 +1,16 @@
 #!/bin/bash
 
-##
-# Login aws
-##
+set -eE -o functrace
 
+failure() {
+  local lineno=$1
+  local msg=$2
+  echo "Failed at $lineno: $msg"
+}
+trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
 
-source "${HOME}/var/workstation-setup/base.sh"
-
+set -o pipefail
+set -o nounset
 
 showHelp() {
    echo "Esecuzione container all'interno del pod"
diff --git a/scripts/aziona-kubectl-exec b/scripts/aziona-kubectl-exec
--- a/scripts/aziona-kubectl-exec
+++ b/scripts/aziona-kubectl-exec
@@ -8,8 +8,17 @@
 #   - Nome container (opzionale, default: nome pod)
 #   - comando da eseguire (opzionale, default: bash)
 ##
+set -eE -o functrace
 
-source $HOME/var/workstation-setup/base.sh
+failure() {
+  local lineno=$1
+  local msg=$2
+  echo "Failed at $lineno: $msg"
+}
+trap 'failure ${LINENO} "$BASH_COMMAND"' ERR
+
+set -o pipefail
+set -o nounset
 
 showHelp() {
    echo "Esecuzione container all'interno del pod"
