add message before command exec

diff --git a/scripts/aziona-exec b/scripts/aziona-exec
--- a/scripts/aziona-exec
+++ b/scripts/aziona-exec
@@ -106,6 +106,11 @@ _exec() {
 }
 
 main(){
+  if [ "${AZIONA_ENABLED:-""}" != "true" ] ; then
+    echo "[ERROR] Before activate aziona env"
+    exit 1
+  fi 
+  echo "${AZIONA_WELCOME_MESSAGE:-""}"
   parser "$@"
   _exec
 }
